### ISSUE TITLE
Could you provide your model weights？

### ISSUE THREAD

**Issue by ztrong-forever** [RobvanGastel/dinov2-finetune#1]
Very nice project. Thank you! Could you provide your model weights? ^-^
![image](https://github.com/RobvanGastel/dinov2-finetune/assets/62659186/8399217e-8d39-49f9-a8c6-c08c5dce1aba)

**Comment by RobvanGastel** [comment]
Thank you! Good catch, I will upload my LoRA and decoder weights in the next commit. Also, I noticed a small mistake in the IoU computation if you're testing the code,
```python
f_iou = IoU(
        task="multiclass",
        num_classes=config.n_classes,
        ignore_index=255,
        average="micro",
    ).cuda()
```
I forgot to specify `average="micro"` in the current commit. I will also fix this in the next commit.

**Comment by RobvanGastel** [comment]
I uploaded the weights and added a short explanation to the README.md :)

**Comment by ztrong-forever** [comment]
> I uploaded the weights and added a short explanation to the README.md :)

Thanks! Look forward to your better output!

**Comment by RobvanGastel** [comment]
I added more pre-trained weights and corrected the IoU computation, how I used torchmetrics was incorrect. If you're ok with it, I will close this issue.
